.TH "C:/Users/Kohli/Desktop/Earth-20000/block.cpp" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/block.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'block.h'\fP
.br
\fC#include 'constants.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "QColor \fBcolors\fP [8]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "QColor \fBcolors\fP[8]"\fBInitial value:\fP
.PP
.nf
 {QColor(Qt::white), QColor(Qt::black), QColor(Qt::red), QColor(Qt::green),
                    QColor(Qt::blue), QColor(Qt::magenta), QColor(Qt::yellow), QColor(Qt::transparent)}
.fi
.PP
Definition at line 10 of file block.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
