.TH "C:/Users/Kohli/Desktop/Earth-20000/block.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/block.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSingleBlock\fP"
.br
.ti -1c
.RI "class \fBBlock\fP"
.br
.ti -1c
.RI "class \fBMonoBlock\fP"
.br
.ti -1c
.RI "class \fBEmptyBlock\fP"
.br
.ti -1c
.RI "class \fBRedBlock\fP"
.br
.ti -1c
.RI "class \fBGreenBlock\fP"
.br
.ti -1c
.RI "class \fBBlueBlock\fP"
.br
.ti -1c
.RI "class \fBMagentaBlock\fP"
.br
.ti -1c
.RI "class \fBYellowBlock\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBOUNDWIDTH\fP   800"
.br
.ti -1c
.RI "#define \fBBOUNDHEIGHT\fP   725"
.br
.ti -1c
.RI "#define \fBBLOCKX\fP   377"
.br
.ti -1c
.RI "#define \fBBLOCKY\fP   627"
.br
.ti -1c
.RI "#define \fBBLOCKW\fP   24"
.br
.ti -1c
.RI "#define \fBBLOCKH\fP   24"
.br
.ti -1c
.RI "#define \fBXRADIUS\fP   100"
.br
.ti -1c
.RI "#define \fBYRADIUS\fP   20"
.br
.ti -1c
.RI "#define \fBOUTLINEX\fP   375"
.br
.ti -1c
.RI "#define \fBOUTLINEY\fP   625"
.br
.ti -1c
.RI "#define \fBOUTLINEW\fP   28"
.br
.ti -1c
.RI "#define \fBOUTLINEH\fP   28"
.br
.ti -1c
.RI "#define \fBSPACE\fP   4"
.br
.ti -1c
.RI "#define \fBBLOCKID\fP   128"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BLOCKH   24"
.PP
Definition at line 23 of file block.h.
.SS "#define BLOCKID   128"
.PP
Definition at line 31 of file block.h.
.SS "#define BLOCKW   24"
.PP
Definition at line 22 of file block.h.
.SS "#define BLOCKX   377"
.PP
Definition at line 20 of file block.h.
.SS "#define BLOCKY   627"
.PP
Definition at line 21 of file block.h.
.SS "#define BOUNDHEIGHT   725"
.PP
Definition at line 19 of file block.h.
.SS "#define BOUNDWIDTH   800"\fBblock.cpp\fP
.PP
Creates an instance of a single block. Involves polymorphism for creating blocks of different colors.
.PP
Contains the prototypes for the methods used in the \fBblock.cpp\fP class.
.PP
Author: Natraj Subramanian 
.PP
Definition at line 18 of file block.h.
.SS "#define OUTLINEH   28"
.PP
Definition at line 29 of file block.h.
.SS "#define OUTLINEW   28"
.PP
Definition at line 28 of file block.h.
.SS "#define OUTLINEX   375"
.PP
Definition at line 26 of file block.h.
.SS "#define OUTLINEY   625"
.PP
Definition at line 27 of file block.h.
.SS "#define SPACE   4"
.PP
Definition at line 30 of file block.h.
.SS "#define XRADIUS   100"
.PP
Definition at line 24 of file block.h.
.SS "#define YRADIUS   20"
.PP
Definition at line 25 of file block.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
