.TH "EnemyShipPart" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnemyShipPart \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemyShip.h>\fP
.PP
Inherited by \fBEnemyShip\fP, \fBEnemyShipBody\fP, \fBEnemyShipTail\fP, \fBEnemyShipWindow\fP, \fBEnemyShipWing1\fP, and \fBEnemyShipWing2\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnemyShipPart\fP (QGraphicsItem *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file enemyShip.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EnemyShipPart::EnemyShipPart (QGraphicsItem * parent = \fC0\fP)"
.PP
Definition at line 6 of file enemyShip.cpp.
.PP
.nf
7         :QGraphicsItem(parent)
8 {
9 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
