.TH "C:/Users/Kohli/Desktop/Earth-20000/enemyShip.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/enemyShip.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsItem>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <QPainter>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnemyShipPart\fP"
.br
.ti -1c
.RI "class \fBEnemyShipBody\fP"
.br
.ti -1c
.RI "class \fBEnemyShipTail\fP"
.br
.ti -1c
.RI "class \fBEnemyShipWing1\fP"
.br
.ti -1c
.RI "class \fBEnemyShipWing2\fP"
.br
.ti -1c
.RI "class \fBEnemyShipWindow\fP"
.br
.ti -1c
.RI "class \fBEnemyShip\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
