.TH "C:/Users/Kohli/Desktop/Earth-20000/form.cpp" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/form.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sleeperthread.h'\fP
.br
\fC#include 'ui_form.h'\fP
.br
\fC#include 'spaceship.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QSound>\fP
.br
\fC#include 'constants.h'\fP
.br
\fC#include 'form.h'\fP
.br
\fC#include 'powerup.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "QPushButton * \fBskipIntro\fP"
.br
.ti -1c
.RI "QTimer * \fBtimer3\fP = new QTimer()"
.br
.ti -1c
.RI "QTimer * \fBtimer4\fP = new QTimer()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "QPushButton* \fBskipIntro\fP"
.PP
Definition at line 19 of file form.cpp.
.SS "QTimer* \fBtimer3\fP = new QTimer()"
.PP
Definition at line 20 of file form.cpp.
.SS "QTimer* \fBtimer4\fP = new QTimer()"
.PP
Definition at line 21 of file form.cpp.
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
