.TH "MagentaBlock" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MagentaBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block.h>\fP
.PP
Inherits \fBBlock\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMagentaBlock\fP ()"
.br
.ti -1c
.RI "QRectF \fBboundingRect\fP () const "
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file block.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MagentaBlock::MagentaBlock ()"
.PP
Definition at line 358 of file block.cpp.
.PP
.nf
359 {
360     //Set color to magenta
361     setColor1(1);
362     setColor2(5);
363 
364     QGraphicsItem *oneBlock = new SingleBlock(this);
365 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "QRectF MagentaBlock::boundingRect () const"
.PP
Reimplemented from \fBBlock\fP.
.PP
Definition at line 367 of file block.cpp.
.PP
.nf
368 {
369     return QRectF();
370 }
.fi
.SS "void MagentaBlock::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = \fC0\fP)"
.PP
Reimplemented from \fBBlock\fP.
.PP
Definition at line 372 of file block.cpp.
.PP
.nf
373 {
374     Q_UNUSED(painter);
375     Q_UNUSED(option);
376     Q_UNUSED(widget);
377 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
