.TH "C:/Users/Kohli/Desktop/Earth-20000/powerup.cpp" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/powerup.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QPainter>\fP
.br
\fC#include <QStyleOption>\fP
.br
\fC#include 'powerup.h'\fP
.br
\fC#include 'constants.h'\fP
.br
\fC#include 'spaceship.h'\fP
.br
\fC#include 'block.h'\fP
.br
\fC#include 'board.h'\fP
.br
\fC#include 'ball.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
