.TH "Ui" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBForm\fP"
.br
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manpreet Kohli CS 340, Fall 2009
.PP
\fBForm.cpp\fP: the source file for the main graphics item window. This class does a lot of stuff including taking care of button presses on the splash screen, level transitions, level editor logic, and key press logic.
.PP
Storyline graphics and slides created by Natraj Subramanian 
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
