.TH "C:/Users/Kohli/Desktop/Earth-20000/ui_form.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/ui_form.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QVariant>\fP
.br
\fC#include <QtGui/QAction>\fP
.br
\fC#include <QtGui/QApplication>\fP
.br
\fC#include <QtGui/QButtonGroup>\fP
.br
\fC#include <QtGui/QGraphicsView>\fP
.br
\fC#include <QtGui/QHeaderView>\fP
.br
\fC#include <QtGui/QLabel>\fP
.br
\fC#include <QtGui/QPushButton>\fP
.br
\fC#include <QtGui/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_Form\fP"
.br
.ti -1c
.RI "class \fBUi::Form\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
