.TH "C:/Users/Kohli/Desktop/Earth-20000/alienmothership.cpp" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/alienmothership.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'alienmothership.h'\fP
.br
\fC#include 'shipsmissiles.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QSound>\fP
.br
\fC#include <QGraphicsView>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'constants.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
