.TH "C:/Users/Kohli/Desktop/Earth-20000/alienspaceship.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/alienspaceship.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsItem>\fP
.br
\fC#include 'alienshipbullet.h'\fP
.br
\fC#include 'ship.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlienSpaceShip\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBID_ALIENSPACESHIP\fP   32"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ID_ALIENSPACESHIP   32"Author: Ivan Collazo File: \fBalienspaceship.cpp\fP Date: 10/05/2009 This class is to creat an alienspaceship in earth:20000 
.PP
Definition at line 10 of file alienspaceship.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
