.TH "C:/Users/Kohli/Desktop/Earth-20000/board.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/board.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
