.TH "C:/Users/Kohli/Desktop/Earth-20000/shipbullet.h" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Kohli/Desktop/Earth-20000/shipbullet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ammo.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShipBullet\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBID_SPACESHIPBULLET\fP   8"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ID_SPACESHIPBULLET   8"Author: Ivan Collazo File: \fBshipbullet.cpp\fP Date: 10/20/2009 This class is to create a space ship bullet in earth:20000 
.PP
Definition at line 10 of file shipbullet.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
