.TH "Ui::MainWindow" 3 "4 Dec 2009" "Earth: 20000" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow.h>\fP
.PP
Inherits \fBUi_MainWindow\fP.
.SH "Detailed Description"
.PP 
Definition at line 78 of file ui_mainwindow.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Earth: 20000 from the source code.
